# Generated by Django 4.2.7 on 2026-05-17 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True, verbose_name='회차 번호')),
                ('draw_date', models.DateTimeField(auto_now_add=True, verbose_name='추첨 일시')),
                ('num1', models.PositiveSmallIntegerField(verbose_name='당첨번호 1')),
                ('num2', models.PositiveSmallIntegerField(verbose_name='당첨번호 2')),
                ('num3', models.PositiveSmallIntegerField(verbose_name='당첨번호 3')),
                ('num4', models.PositiveSmallIntegerField(verbose_name='당첨번호 4')),
                ('num5', models.PositiveSmallIntegerField(verbose_name='당첨번호 5')),
                ('num6', models.PositiveSmallIntegerField(verbose_name='당첨번호 6')),
                ('bonus', models.PositiveSmallIntegerField(verbose_name='보너스 번호')),
            ],
            options={
                'verbose_name': '추첨 결과',
                'verbose_name_plural': '추첨 결과 목록',
                'ordering': ['-round_no'],
            },
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveSmallIntegerField()),
                ('num2', models.PositiveSmallIntegerField()),
                ('num3', models.PositiveSmallIntegerField()),
                ('num4', models.PositiveSmallIntegerField()),
                ('num5', models.PositiveSmallIntegerField()),
                ('num6', models.PositiveSmallIntegerField()),
                ('purchase_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], max_length=10, verbose_name='구매 방식')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('rank', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1등'), (2, '2등'), (3, '3등'), (4, '4등'), (5, '5등')], null=True, verbose_name='당첨 등수')),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='lotto.lottodrawing', verbose_name='참여 회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': '구매 복권',
                'verbose_name_plural': '구매 복권 목록',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
